codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "0...10"
  status:
    project:
      default:
        target: 10%
        threshold: 0.5%
    patch:
      default:
        target: 10%

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false
